INSERT INTO Article (article_id, article_author, creation_date, article_title, article_url,description) values (nextval('articles_generator'), 'Oracle Cloud Native','07-07-2019','Jenkins X','https://cloudnative.oracle.com/','Demo');
INSERT INTO Article (article_id, article_author, creation_date, article_title, article_url,description) values (nextval('articles_generator'), 'Oracle Cloud Native','05-07-2019','Oracle Container Engine for Kubernetes','https://cloudnative.oracle.com/','Demo');
INSERT INTO Article (article_id, article_author, creation_date, article_title, article_url,description) values (nextval('articles_generator'), 'Oracle Cloud Native','05-07-2019','Oracle Container Engine for Kubernetes','https://cloudnative.oracle.com/','Demo');
INSERT INTO Article (article_id, article_author, creation_date, article_title, article_url,description) values (nextval('articles_generator'), 'Oracle Cloud Native','05-07-2019','Oracle Container Engine for Kubernetes','https://cloudnative.oracle.com/','Demo');
INSERT INTO Article (article_id, article_author, creation_date, article_title, article_url,description) values (nextval('articles_generator'), 'Oracle Cloud Native','05-07-2019','Oracle Container Engine for Kubernetes','https://cloudnative.oracle.com/','Demo');
INSERT INTO Article (article_id, article_author, creation_date, article_title, article_url,description) values (nextval('articles_generator'), 'Oracle Cloud Native','05-07-2019','Oracle Container Engine for Kubernetes','https://cloudnative.oracle.com/','Demo');
INSERT INTO Article (article_id, article_author, creation_date, article_title, article_url,description) values (nextval('articles_generator'), 'Oracle Cloud Native','05-07-2019','Oracle Container Engine for Kubernetes','https://cloudnative.oracle.com/','Demo');
INSERT INTO Article (article_id, article_author, creation_date, article_title, article_url,description) values (nextval('articles_generator'), 'Oracle Cloud Native','05-07-2019','Oracle Container Engine for Kubernetes','https://cloudnative.oracle.com/','Demo');
INSERT INTO Article (article_id, article_author, creation_date, article_title, article_url,description) values (nextval('articles_generator'), 'Oracle Cloud Native','05-07-2019','Oracle Container Engine for Kubernetes','https://cloudnative.oracle.com/','Demo');
